name: BetterServer
version: '${project.version}'
main: BetterServer.Main
api-version: 1.19
authors: [ EthanGarey ]
commands:
  trash:
    permission: BetterServer.permissions.commands.trash
  fly:
    permission: BetterServer.permissions.commands.flight.toggle
  walkspeed:
    permission: BetterServer.permissions.commands.walk.speed
  flyspeed:
    permission: BetterServer.permissions.commands.flight.speed
  msg:
    aliases: [ "message", "w", "tell" ]
    permission: BetterServer.permissions.commands.message
  reply:
    aliases: [ "r", "reply" ]
    permission: BetterServer.permissions.commands.message.reply
  teleport:
    aliases: [ "tp" ]
    permission: BetterServer.permissions.commands.teleport
  tpall:
    aliases: [ "bringall" ]
    permission: BetterServer.permissions.commands.teleport.others.all
  socialspy:
    permission: BetterServer.permissions.socialspy
  #Gamemode#
  gamemode:
    aliases: [ "gm" ]
    permission: BetterServer.permissions.gamemode
  gmc:
    permission: BetterServer.permissions.gamemode
  gms:
    permission: BetterServer.permissions.gamemode
  gma:
    permission: BetterServer.permissions.gamemode
  gmsp:
    permission: BetterServer.permissions.gamemode
  #Gamemode#
  betterserver:
    usage: "§4§lUsage: /BetterServer [<help>,<update>, <reload>]"

    permission: BetterServer.permissions.bettercommands.menu
  god:
    usage: §a§l/god [<player>]
    permission: BetterServer.permissions.god
  clearchat:
    aliases: [ "cc" ]
    permission: BetterServer.permissions.clearchat
  clear:
    permission: BetterServer.permissions.clear
    aliases: [ "ci", "clearinventory" ]
  invsee:
    aliases: [ "viewinventory" ]
    permission: BetterServer.permissions.invsee
  back:
    permission: BetterServer.permissions.back
  give:
    permission: BetterServer.permissions.give
    aliases: [ "i" ]
  #tools#
  workbench:
    aliases: [ "craft", "craftingtable" ]
    permission: BetterServer.permissions.tools.workbench

  tool:
    permission: BetterServer.permissions.tools
  tools:
    permission: BetterServer.permissions.tools.list
    #Tools#
  mutechat:
    permission: BetterServer.permissions.chat.mutechat
  more:
    permission: BetterServer.permissions.more
  rules:
    permission: BetterServer.permissions.rules
  spawn:
    permission: BetterServer.permissions.spawn
  setspawn:
    permission: BetterServer.permissions.spawn.set
  home:
    permission: BetterServer.permissions.home.go
    aliases: [ "homes" ]
  sethome:
    permission: BetterServer.permissions.home.set
    aliases: [ "sethome", "createhome" ]
  delhome:
    permission: BetterServer.permissions.home.delete
    aliases: [ "remhome", "removehome" ]
  motd:
    permission: BetterServer.permissions.motd
